### ISSUE TITLE
Multiple cwd for dynamic folders

### ISSUE THREAD

**Issue by dominikwilkowski** [Manabu-GT/grunt-auto-install#10]
Hey,

Great plugin but I see the biggest potential for it when we don't know how many sub-folders there are which need `npm install`.
In that case automating it make a lot of sense.

Something like:

```js
auto_install: {
	subdir: {
		options: {
			stdout: true,
			stderr: true,
			failOnError: true,
			npm: true,
			bower: false,
		},
		src: [
			'./*/',
			'!./node_modules',
		],
	},
},
```

What do you think?

**Comment by sieira** [comment]
+1000 for that

**Comment by sieira** [comment]
This PR adds three options:

 - recursive: It's false by default, when true, will perform the install recursively
 - match: It's `'.*'` (always true) by default, will perform the install on the directories matching this regexp when recursive is set to true
 - exclude: `'/(?=a)b/'` (always false - a is b -) will ignore the directories matching this pattern when performing the install.

Both match and exclude could potentially be arrays of regexps, I can perform that change if you consider it appropriate.

As mentioned, I was unable to add the tests since I'm new to bower, but I can spend some time doing it if you consider this functionality as a potential improvement of grunt-auto-install

**Comment by Manabu-GT** [comment]
@sieira Thanks for the PR. If you can also add the tests, that would be great. Once you add some test cases for this change, I will review and merge the PR.

**Comment by sieira** [comment]
Done. It ended by being a bit of a major change... I hope you'll like it

**Comment by dominikwilkowski** [comment]
awesome! :+1:

**Comment by Manabu-GT** [comment]
The change is now in v0.3.0. Thanks for your support.:smile:
